# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.18 is version 38
loaderVersion="[40,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="LGPL-3.0"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Traben-0/EmissiveMod/issues"
# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false

[[mods]]
modId="etf"
version="${version}"
displayName="Entity Texture Features"
displayURL="https://github.com/Traben-0/EmissiveMod"
logoFile="icon.png"
credits=""
authors=["Traben", "CanadianBacon"]
description='''
  Optifine format compatible:
 - Random & Custom textures
 - Emissive textures
With features such as:
 - Blinking textures
 - Player Skin textures
  '''

[[dependencies.etf]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="CLIENT"

[[dependencies.etf]]
modId="cloth_config"
mandatory=true
versionRange="[6.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.etf]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="CLIENT"